"""Upload the full "From Eden to Timbuktu" documentary to YouTube as UNLISTED.

Single-shot: uploads the post-produced MP4 (intro + outro + logo already baked in),
sets the full metadata pack (viral description + real chapters + keyword tags),
creates/uses the "From Eden to Timbuktu" playlist, and posts the controversial-but-
professional pinned-comment text. Pinning + the synthetic-content flag + flip-to-Public
are Studio-only manual clicks (Tommy does those after QC).

Privacy is forced to 'unlisted' so the encode + pinned comment can be QC'd before the
world sees it. Mirrors the working scripts/upload-anchor-doc.py resumable pattern.

Usage: python scripts/upload-eden-full-doc.py
"""
import sys
from pathlib import Path

from googleapiclient.http import MediaFileUpload

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from src.youtube.client import YouTubeClient

# Post-produced output (intro/outro/logo wrapped). Falls back to raw render if absent.
VIDEO_PATH = ROOT / "output" / "eden-full-doc_final.mp4"
RAW_PATH = ROOT / "output" / "renders" / "eden-full-doc.mp4"

# Thumbnail — recommended pick (swap to 01_hebrews / 03_origin to change lead art).
THUMBNAIL = ROOT / "output" / "thumbnails" / "eden-full" / "02_erased.png"

TITLE = "FROM EDEN TO TIMBUKTU: The Hidden History of the Black Hebrews | Full Documentary"

DESCRIPTION = """Before there was a Europe, there was a garden. Before a single stone of Rome was laid, before the words "black" and "white" were ever used to divide one man from another, there was a dark and shining people walking between two rivers, in the oldest civilization this earth has ever known.

This is the full documentary. From the Garden of Eden to the libraries of Timbuktu. From the first empire on earth to the last great Black kingdoms of West Africa. We follow the trail of historian Rudolph R. Windsor's "From Babylon to Timbuktu," weigh it against the Scriptures, and lay the receipts on the table across six thousand years of hidden history.

They remember the pyramids and forget the faces. They study the laws and erase the complexion. This is the record they never assembled in one place.

Stay till the end. The last chapter is the part that changes everything.

CHAPTERS
0:00 Introduction: The Journey Begins
0:28 Cold Open: A People Between Two Rivers
1:45 Introduction: The Claim We Will Examine
4:24 Part I - Ancient Black Civilization
14:14 Part II - The Origin of the White Race
21:45 Part III - Afro-Asian Culture Goes to Europe
32:53 Part IV - The Original Black Jews
45:38 Part V - The Lineage of the Messiah
52:44 Part VI - The Storm Out of Arabia
1:00:15 Part VII - Black Civilization in Africa
1:14:12 Part VIII - The Final Dispersion
1:27:49 Conclusion - The Awakening
1:34:11 Where Do You Stand?

SOURCES
The Scriptures (1611 King James Version). The historian Rudolph R. Windsor's "From Babylon to Timbuktu" (1969). Ancient writers including Herodotus and Josephus. This is an original work based on the historical themes documented by Windsor - it is not a reproduction of his book. We tell you as we go which parts are settled history and which parts are interpretation.

Subscribe and turn on notifications for more.
Join the community: https://t.me/aibiblegospels

- Q&A -
Q: What is this documentary's central claim?
A: That civilization itself began among dark-skinned peoples of the ancient Near East and Africa - that the patriarchs, prophets, kings of Israel, and the Messiah were a melanated people - and that after the great scatterings their descendants walked into Africa, built empires, and were carried across an ocean.

Q: Who made this video?
A: AI Bible Gospels, a faith-tech project by Tommy Lee that uses AI to bring Scripture to life from a cultural perspective underrepresented in biblical media.

Q: What sources does it use?
A: The 1611 KJV Scriptures, Rudolph R. Windsor's "From Babylon to Timbuktu," and ancient writers including Herodotus and Josephus.

- CONTENT TRANSPARENCY -
This documentary uses AI-assisted narration and AI-generated imagery to illustrate a human-written script. The narration script, historical claims, and Scripture quotations are written and verified by a person, not generated by AI.

- ABOUT AI BIBLE GOSPELS -
AI Bible Gospels (@AIBIBLEGOSPELS) is a faith-tech brand founded by Tommy Lee that uses AI to narrate Scripture word-for-word from a cultural perspective underrepresented in biblical media. Flagship project: Faith Walk Live, the live tracker for Minister Zay's 3,000-mile walk from Philadelphia to California.

Website: https://aibiblegospels.com
Faith Walk Live: https://faithwalklive.com
YouTube: https://www.youtube.com/@AIBIBLEGOSPELS
Contact: aibiblegospels444@gmail.com

#AIBibleGospels #BlackHebrews #BlackHistory #BibleHistory #FromEdenToTimbuktu #12TribesOfIsrael"""

# YouTube caps the COMBINED tag length at ~500 chars (incl. the quotes it adds
# around multi-word tags + commas). Keep this list lean; raw sum ~300 chars.
TAGS = [
    "black hebrews", "black hebrew israelites", "from eden to timbuktu",
    "hidden history", "12 tribes of israel", "table of nations", "cush", "nimrod",
    "rudolph windsor", "from babylon to timbuktu", "origin of the white race",
    "black jews", "timbuktu", "bible history", "hebrew israelite history",
    "who are the real israelites", "ai bible gospels", "black history documentary",
]

CATEGORY_ID = "27"  # Education

PINNED_COMMENT = """Here is the claim this documentary puts on the table: that the first civilization on earth, the patriarchs, the kings of Israel, and the Messiah himself were a dark-skinned, melanated people - and that the version most of us were handed in school quietly erased their faces.

You don't have to take my word for it. Every Scripture is on screen and every source is named - check them for yourself. Then tell me in the replies: which part did you already know, and which part did they never teach you? Timestamp the exact moment that challenged you the most.

Prove all things; hold fast that which is good."""

PLAYLIST_TITLE = "From Eden to Timbuktu"
PLAYLIST_DESCRIPTION = (
    "The hidden history of the Black Hebrews - from the Garden of Eden to the "
    "empires of Timbuktu. A 12 Tribes documentary series from AI Bible Gospels, "
    "following the trail of Rudolph R. Windsor's 'From Babylon to Timbuktu.'"
)


def main():
    video = VIDEO_PATH if VIDEO_PATH.exists() else RAW_PATH
    if not video.exists():
        sys.exit(f"MISSING: neither {VIDEO_PATH} nor {RAW_PATH} exists")
    if video == RAW_PATH:
        print("WARNING: post-produced file not found; uploading RAW render (no intro/outro).")
        print("         Chapter timestamps assume the branded intro is present - abort if unsure.")

    print(f"Video: {video.relative_to(ROOT)} ({video.stat().st_size / 1e9:.2f} GB)")
    print()

    yt = YouTubeClient()
    youtube = yt.youtube

    # 1. Upload video (resumable) as UNLISTED
    print("[1/4] Uploading video as UNLISTED (resumable, may take 10-25 min for ~2 GB)...")
    body = {
        "snippet": {
            "title": TITLE,
            "description": DESCRIPTION,
            "tags": TAGS,
            "categoryId": CATEGORY_ID,
        },
        "status": {
            "privacyStatus": "unlisted",
            "selfDeclaredMadeForKids": False,
            "madeForKids": False,
        },
    }
    media = MediaFileUpload(str(video), chunksize=8 * 1024 * 1024, resumable=True)
    request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)
    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"     Upload progress: {int(status.progress() * 100)}%")
    video_id = response["id"]
    video_url = f"https://www.youtube.com/watch?v={video_id}"
    print(f"     Done. video_id = {video_id}")
    print(f"     URL: {video_url}")

    # 2. Set thumbnail
    if THUMBNAIL.exists():
        print(f"\n[2/5] Setting thumbnail ({THUMBNAIL.name})...")
        yt.set_thumbnail(video_id, str(THUMBNAIL))
        print("     Done.")
    else:
        print(f"\n[2/5] Thumbnail not found ({THUMBNAIL.name}) - skipping, set in Studio.")

    # 3. Find or create playlist
    print(f"\n[3/5] Finding or creating playlist '{PLAYLIST_TITLE}'...")
    playlists = yt.list_playlists()
    target = next((p for p in playlists if p["snippet"]["title"] == PLAYLIST_TITLE), None)
    if target:
        playlist_id = target["id"]
        print(f"     Found existing. id = {playlist_id}")
    else:
        new_pl = yt.create_playlist(PLAYLIST_TITLE, PLAYLIST_DESCRIPTION, "public")
        playlist_id = new_pl["id"]
        print(f"     Created. id = {playlist_id}")

    # 4. Add video to playlist
    print(f"\n[4/5] Adding video to playlist...")
    yt.add_to_playlist(playlist_id, video_id)
    print(f"     Done.")

    # 5. Post pinned-comment text (pin click is Studio-only)
    print(f"\n[5/5] Posting pinned-comment text (you click 'Pin' in Studio)...")
    comment_body = {
        "snippet": {
            "videoId": video_id,
            "topLevelComment": {"snippet": {"textOriginal": PINNED_COMMENT}},
        }
    }
    comment_resp = youtube.commentThreads().insert(part="snippet", body=comment_body).execute()
    print(f"     Done. comment_id = {comment_resp['id']}")

    print("\n" + "=" * 78)
    print("UPLOAD COMPLETE -- video is UNLISTED. Manual steps before Public:\n")
    print(f"  1. Watch the encoded player: {video_url}")
    print(f"  2. Studio > this video > Show more > Altered/synthetic content = YES.")
    print(f"  3. Studio > Comments > 3-dot on your comment > Pin.")
    print(f"  4. Studio > Visibility > Public (or Schedule), then Save.")
    print(f"  5. (Recommended) Add a custom thumbnail - biggest CTR lever.")
    print("=" * 78)


if __name__ == "__main__":
    main()
