"""Upload Eden -> Timbuktu Part 1 to YouTube as PRIVATE (QC before going Public).

Uses src/youtube/client.py::upload_video. Metadata mirrors docs/eden-part1-publish.md with
the real chapter timestamps from the assembled cut. Privacy is forced to 'private' — the
human must set "Altered/synthetic content = Yes" in Studio and flip to Public afterward.

Usage: python scripts/upload-eden-part1.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from src.youtube.client import YouTubeClient

VIDEO = ROOT / "output" / "renders" / "eden-part1.mp4"
THUMB = ROOT / "output" / "thumbnails" / "eden-part1" / "01_hebrews_1280x720.png"

TITLE = "From Eden to Timbuktu: The Hidden History of the Black Hebrews | Part 1 — Ancient Black Civilization"

DESCRIPTION = """Before there was a Europe, there was a garden. This is Part 1 of "From Eden to Timbuktu" — a documentary journey through the hidden history of the Black Hebrews, beginning where civilization itself began: between the Tigris and the Euphrates, in the land the Bible traces to Cush.

We follow the trail of historian Rudolph R. Windsor's "From Babylon to Timbuktu," weigh it against the Scriptures, and put the receipts on the table — Genesis 2, the Table of Nations in Genesis 10, the black-headed people of Sumer, and the line that built the first empire on earth.

This is Part 1 of a series. New chapters are in production.

CHAPTERS
0:00 — Cold Open: A People Between Two Rivers
1:16 — Introduction: The Claim We're Going to Examine
3:52 — Part One: Ancient Black Civilization
6:57 — The Builders of Babylon
11:42 — Two Ethiopias & the Scattering at Babel

SCRIPTURES REFERENCED
Genesis 2:10-14 - Genesis 10:6-10 (the Table of Nations)

Subscribe and turn on notifications - Part 2 ("Where Did the White Race Begin?") is next.
Join the community: https://t.me/aibiblegospels

- Q&A -
Q: Who made this video?
A: AI Bible Gospels, a faith-tech project by Tommy Lee using AI to bring Scripture to life from a cultural perspective.

Q: Is this Part 1 of a series?
A: Yes. "From Eden to Timbuktu" is a multi-part documentary; new chapters release on this channel.

Q: What sources does it use?
A: The Scriptures (1611 KJV), the historian Rudolph R. Windsor's "From Babylon to Timbuktu," and ancient writers including Herodotus and Josephus.

- CONTENT TRANSPARENCY -
This documentary uses AI-assisted narration and AI-generated imagery to illustrate a human-written script. The narration script, historical claims, and Scripture quotations are written and verified by a person, not generated by AI.

- ABOUT AI BIBLE GOSPELS -
AI Bible Gospels (@AIBIBLEGOSPELS) is a faith-tech brand founded by Tommy Lee that uses AI to narrate Scripture word-for-word from a cultural perspective underrepresented in biblical media. Flagship project: Faith Walk Live, the live tracker for Minister Zay's 3,000-mile walk from Philadelphia to California.

Website: https://aibiblegospels.com
Faith Walk Live: https://faithwalklive.com
YouTube: https://www.youtube.com/@AIBIBLEGOSPELS
Contact: aibiblegospels444@gmail.com

#AIBibleGospels #BlackHebrews #BlackHistory #BibleHistory #FromEdenToTimbuktu"""

TAGS = [
    "black hebrews", "black hebrew israelites", "from eden to timbuktu", "hidden history",
    "ancient black civilization", "12 tribes of israel", "table of nations", "genesis 10",
    "cush", "nimrod", "sumer", "mesopotamia", "babylon", "rudolph windsor",
    "from babylon to timbuktu", "bible history", "black history", "ai bible gospels",
    "biblical documentary",
]


def main():
    if not VIDEO.exists():
        sys.exit(f"Render not found: {VIDEO}")
    print(f"Uploading {VIDEO.name} ({VIDEO.stat().st_size/1e6:.0f} MB) as PRIVATE...")
    yt = YouTubeClient()
    vid = yt.upload_video(
        filepath=str(VIDEO),
        title=TITLE,
        description=DESCRIPTION,
        tags=TAGS,
        category_id="27",          # Education
        privacy="private",
        made_for_kids=False,
        thumbnail=str(THUMB) if THUMB.exists() else None,
        on_progress=lambda pct: print(f"  upload {pct}%"),
    )
    print(f"\nDONE. Video ID: {vid}")
    print(f"Watch (private): https://studio.youtube.com/video/{vid}/edit")
    print("\nMANUAL STEPS before Public:")
    print("  1. Studio > this video > Altered/synthetic content = YES (AI imagery + voice)")
    print("  2. QC the cut, then set Public (or schedule before 2026-07-08)")
    print("  3. Add to a new 'From Eden to Timbuktu' playlist")


if __name__ == "__main__":
    main()
